remote_theme: itstorque/jekyll-shell-theme
title_from_headings:
  enabled: false
  strip_title: true
  collections: true

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-titles-from-headings
